import type {
  PipelineRunResult,
  ERDiagramResult,
  ChainPlanResult,
  GeneratedTestFile,
  ValidationError,
} from '../types.js';

// ===== Reporter Types =====

export interface ReportOutput {
  format: 'html' | 'json' | 'markdown';
  content: string;
  filename: string;
}

// ===== JSON Reporter =====

export function generateJsonReport(result: PipelineRunResult): ReportOutput {
  const serializable = {
    modules: result.modules,
    erDiagrams: Object.fromEntries(
      Array.from(result.erDiagrams.entries()).map(([k, v]) => [
        k,
        { tables: v.tables.length, relations: v.relations.length, mermaidText: v.mermaidText },
      ]),
    ),
    chainPlans: Object.fromEntries(
      Array.from(result.chainPlans.entries()).map(([k, v]) => [
        k,
        { chains: v.chains.length, totalSteps: v.totalSteps },
      ]),
    ),
    generatedFiles: result.generatedFiles.map((f) => ({
      filePath: f.filePath,
      module: f.module,
      chain: f.chain,
    })),
    validationErrors: result.validationErrors,
    duration: result.duration,
  };

  return {
    format: 'json',
    content: JSON.stringify(serializable, null, 2),
    filename: 'opencroc-report.json',
  };
}

// ===== Markdown Reporter =====

export function generateMarkdownReport(result: PipelineRunResult): ReportOutput {
  const lines: string[] = [
    '# OpenCroc Report',
    '',
    `**Duration**: ${result.duration}ms`,
    `**Modules**: ${result.modules.length} (${result.modules.join(', ')})`,
    '',
    '## ER Diagrams',
    '',
  ];

  for (const [mod, er] of result.erDiagrams) {
    lines.push(`### ${mod}`);
    lines.push(`- Tables: ${er.tables.length}`);
    lines.push(`- Relations: ${er.relations.length}`);
    lines.push('');
  }

  lines.push('## Chain Plans', '');
  for (const [mod, plan] of result.chainPlans) {
    lines.push(`### ${mod}`);
    lines.push(`- Chains: ${plan.chains.length}`);
    lines.push(`- Total Steps: ${plan.totalSteps}`);
    lines.push('');
  }

  lines.push(`## Generated Files (${result.generatedFiles.length})`, '');
  for (const f of result.generatedFiles) {
    lines.push(`- \`${f.filePath}\` (${f.module} / ${f.chain})`);
  }

  if (result.validationErrors.length > 0) {
    lines.push('', '## Validation Issues', '');
    const errors = result.validationErrors.filter((e) => e.severity === 'error');
    const warnings = result.validationErrors.filter((e) => e.severity === 'warning');
    if (errors.length > 0) {
      lines.push(`### Errors (${errors.length})`, '');
      for (const e of errors) {
        lines.push(`- **[${e.module}]** ${e.field}: ${e.message}`);
      }
    }
    if (warnings.length > 0) {
      lines.push(`### Warnings (${warnings.length})`, '');
      for (const w of warnings) {
        lines.push(`- **[${w.module}]** ${w.field}: ${w.message}`);
      }
    }
  }

  lines.push('', '---', '*Generated by [OpenCroc](https://github.com/opencroc/opencroc)*');

  return {
    format: 'markdown',
    content: lines.join('\n'),
    filename: 'opencroc-report.md',
  };
}

// ===== HTML Reporter =====

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function erSummaryRows(erDiagrams: Map<string, ERDiagramResult>): string {
  const rows: string[] = [];
  for (const [mod, er] of erDiagrams) {
    rows.push(`<tr><td>${escapeHtml(mod)}</td><td>${er.tables.length}</td><td>${er.relations.length}</td></tr>`);
  }
  return rows.join('\n');
}

function chainSummaryRows(chainPlans: Map<string, ChainPlanResult>): string {
  const rows: string[] = [];
  for (const [mod, plan] of chainPlans) {
    rows.push(`<tr><td>${escapeHtml(mod)}</td><td>${plan.chains.length}</td><td>${plan.totalSteps}</td></tr>`);
  }
  return rows.join('\n');
}

function fileListRows(files: GeneratedTestFile[]): string {
  return files
    .map((f) => `<tr><td><code>${escapeHtml(f.filePath)}</code></td><td>${escapeHtml(f.module)}</td><td>${escapeHtml(f.chain)}</td></tr>`)
    .join('\n');
}

function validationRows(errors: ValidationError[]): string {
  return errors
    .map(
      (e) =>
        `<tr class="${e.severity}"><td><span class="badge ${e.severity}">${e.severity}</span></td><td>${escapeHtml(e.module)}</td><td>${escapeHtml(e.field)}</td><td>${escapeHtml(e.message)}</td></tr>`,
    )
    .join('\n');
}

export function generateHtmlReport(result: PipelineRunResult): ReportOutput {
  const totalTables = Array.from(result.erDiagrams.values()).reduce((s, e) => s + e.tables.length, 0);
  const totalRelations = Array.from(result.erDiagrams.values()).reduce((s, e) => s + e.relations.length, 0);
  const totalChains = Array.from(result.chainPlans.values()).reduce((s, p) => s + p.chains.length, 0);
  const totalSteps = Array.from(result.chainPlans.values()).reduce((s, p) => s + p.totalSteps, 0);
  const errorCount = result.validationErrors.filter((e) => e.severity === 'error').length;
  const warnCount = result.validationErrors.filter((e) => e.severity === 'warning').length;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>OpenCroc Report</title>
<style>
  :root { --bg: #0d1117; --fg: #c9d1d9; --card: #161b22; --border: #30363d; --accent: #58a6ff; --green: #3fb950; --yellow: #d29922; --red: #f85149; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; background: var(--bg); color: var(--fg); padding: 2rem; }
  h1 { color: var(--accent); margin-bottom: 0.25rem; }
  .subtitle { color: #8b949e; margin-bottom: 2rem; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1.25rem; }
  .card .label { font-size: 0.85rem; color: #8b949e; }
  .card .value { font-size: 2rem; font-weight: 700; color: var(--accent); }
  .card .value.green { color: var(--green); }
  .card .value.yellow { color: var(--yellow); }
  .card .value.red { color: var(--red); }
  section { margin-bottom: 2rem; }
  h2 { color: var(--fg); border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; margin-bottom: 1rem; }
  table { width: 100%; border-collapse: collapse; background: var(--card); border-radius: 8px; overflow: hidden; }
  th, td { text-align: left; padding: 0.6rem 1rem; border-bottom: 1px solid var(--border); }
  th { background: #21262d; color: #8b949e; font-weight: 600; font-size: 0.85rem; text-transform: uppercase; }
  tr:last-child td { border-bottom: none; }
  code { background: #21262d; padding: 0.15rem 0.4rem; border-radius: 4px; font-size: 0.85rem; }
  .badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 12px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
  .badge.error { background: rgba(248,81,73,0.15); color: var(--red); }
  .badge.warning { background: rgba(210,153,34,0.15); color: var(--yellow); }
  footer { margin-top: 3rem; text-align: center; color: #484f58; font-size: 0.85rem; }
  footer a { color: var(--accent); text-decoration: none; }
</style>
</head>
<body>
<h1>OpenCroc Report</h1>
<p class="subtitle">Generated in ${result.duration}ms &middot; ${result.modules.length} module(s)</p>

<div class="grid">
  <div class="card"><div class="label">Modules</div><div class="value">${result.modules.length}</div></div>
  <div class="card"><div class="label">Tables</div><div class="value">${totalTables}</div></div>
  <div class="card"><div class="label">Relations</div><div class="value">${totalRelations}</div></div>
  <div class="card"><div class="label">Chains</div><div class="value">${totalChains}</div></div>
  <div class="card"><div class="label">Steps</div><div class="value">${totalSteps}</div></div>
  <div class="card"><div class="label">Files</div><div class="value green">${result.generatedFiles.length}</div></div>
  <div class="card"><div class="label">Errors</div><div class="value${errorCount > 0 ? ' red' : ''}">${errorCount}</div></div>
  <div class="card"><div class="label">Warnings</div><div class="value${warnCount > 0 ? ' yellow' : ''}">${warnCount}</div></div>
</div>

<section>
<h2>ER Diagrams</h2>
<table>
<thead><tr><th>Module</th><th>Tables</th><th>Relations</th></tr></thead>
<tbody>${erSummaryRows(result.erDiagrams)}</tbody>
</table>
</section>

<section>
<h2>Chain Plans</h2>
<table>
<thead><tr><th>Module</th><th>Chains</th><th>Steps</th></tr></thead>
<tbody>${chainSummaryRows(result.chainPlans)}</tbody>
</table>
</section>

<section>
<h2>Generated Files (${result.generatedFiles.length})</h2>
<table>
<thead><tr><th>File</th><th>Module</th><th>Chain</th></tr></thead>
<tbody>${fileListRows(result.generatedFiles)}</tbody>
</table>
</section>

${
  result.validationErrors.length > 0
    ? `<section>
<h2>Validation Issues (${result.validationErrors.length})</h2>
<table>
<thead><tr><th>Severity</th><th>Module</th><th>Field</th><th>Message</th></tr></thead>
<tbody>${validationRows(result.validationErrors)}</tbody>
</table>
</section>`
    : ''
}

<footer>
  Generated by <a href="https://github.com/opencroc/opencroc">OpenCroc</a>
</footer>
</body>
</html>`;

  return {
    format: 'html',
    content: html,
    filename: 'opencroc-report.html',
  };
}

// ===== Report Orchestrator =====

const REPORTERS: Record<string, (result: PipelineRunResult) => ReportOutput> = {
  html: generateHtmlReport,
  json: generateJsonReport,
  markdown: generateMarkdownReport,
};

/**
 * Generate reports in the specified formats.
 */
export function generateReports(
  result: PipelineRunResult,
  formats: ('html' | 'json' | 'markdown')[] = ['html'],
): ReportOutput[] {
  return formats.map((fmt) => {
    const gen = REPORTERS[fmt];
    if (!gen) throw new Error(`Unknown report format: "${fmt}". Available: ${Object.keys(REPORTERS).join(', ')}`);
    return gen(result);
  });
}

// ===== Advanced Reporters (v1.2) =====
export {
  classifyFailure,
  buildFailureSummary,
  aggregateLogCompletion,
  parseApiDomain,
  buildBackendChecklist,
  renderChecklistMarkdown,
} from './checklist-reporter.js';

export {
  buildWorkorders,
  renderWorkordersMarkdown,
} from './workorder-reporter.js';
export type { BuildWorkordersOptions } from './workorder-reporter.js';

export {
  TokenTracker,
  renderTokenReportMarkdown,
} from './token-reporter.js';
